#+TITLE: mrroman's blog
#+HTML_DOCTYPE: html5
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="/css/style.css">
#+OPTIONS: toc:nil num:nil author:nil timestamp:nil html-style:nil

* Blog engine version 0.1

I've started my first Guile Scheme app. It is a small generator of blog.
You can see the result this small post that I wrote here.

I thought about writing small app to learn Scheme - Lisp derivative.
I was aquainted already with Clojure (another Lisp derivative), so
parenthesis and list wasn't novelty for me, but it was not what I expected.
It wasn't bad, but it meant getting used to another idea for the development,
different toolset and libraries.

I know that there are other, more sophisticated Scheme implementations
like Racket, but Guile felt to me lighter and the module system was more
like I was used to already. There was even a HTTP client and server
in the standard library :).

GNU Guile is available almost in every Linux distribution and on MacOS X.
It is just one command to install it:

#+BEGIN_SRC shell
  <your apt/yum/pacman/brew> install guile
#+END_SRC
